	; Standard tilemap data; see format.txt in TMAPDATA for what this is comprised of.
	.incbin "PRG/TMAPDATA/TMAP0C.bin"
	
	; NOTE: NORMALLY this is the damage factor table, but it's used as an enable/disable
	; for Flash Stopper instead, and Mega Buster (0) is employed for the damage factor.
	; Per-object-slot-ID enable for Flash Stopper (non-zero allows)
	.org Player_WeaponDamageTable	; <-- help enforce this table *here*
PRG044_FlashStopperEnTable:
	.byte $00	; $00
	.byte $00	; $01 SPRSLOTID_PLAYER
	.byte $00	; $02 SPRSLOTID_PLAYERSHOT
	.byte $00	; $03 SPRSLOTID_DEFLECTEDSHOT
	.byte $00	; $04 SPRSLOTID_RUSH
	.byte $00	; $05 SPRSLOTID_TOADRAINCAN
	.byte $00	; $06 SPRSLOTID_BALLOON
	.byte $00	; $07 SPRSLOTID_DIVEMISSILE
	.byte $00	; $08 SPRSLOTID_RINGBOOMERANG
	.byte $00	; $09 SPRSLOTID_DRILLBOMB
	.byte $00	; $0A SPRSLOTID_DUSTCRUSHER
	.byte $00	; $0B SPRSLOTID_WIREADAPTER
	.byte $00	; $0C SPRSLOTID_PHARAOHSHOT
	.byte $00	; $0D SPRSLOTID_PHARAOHOVERH
	.byte $00	; $0E
	.byte $00	; $0F SPRSLOTID_SKULLBARRIER
	.byte $FF	; $10 SPRSLOTID_TAKETETNO
	.byte $FF	; $11 SPRSLOTID_TAKETETNO_PROP
	.byte $FF	; $12 SPRSLOTID_HOVER
	.byte $FF	; $13 SPRSLOTID_TOMBOY
	.byte $FF	; $14 SPRSLOTID_SASOREENU
	.byte $00	; $15 SPRSLOTID_SASOREENU_SPAWNER
	.byte $00	; $16 SPRSLOTID_BATTAN
	.byte $00	; $17
	.byte $FF	; $18 SPRSLOTID_SWALLOWN
	.byte $FF	; $19 SPRSLOTID_COSWALLOWN
	.byte $FF	; $1A SPRSLOTID_WALLBLASTER
	.byte $FF	; $1B SPRSLOTID_WALLBLASTER_SHOT
	.byte $FF	; $1C SPRSLOTID_100WATTON
	.byte $FF	; $1D SPRSLOTID_100WATTON_SHOT
	.byte $FF	; $1E SPRSLOTID_100WATTON_SHOT_BURST
	.byte $FF	; $1F SPRSLOTID_RATTON
	.byte $00	; $20 SPRSLOTID_RMRAINBOW_CTL1
	.byte $00	; $21 SPRSLOTID_RMRAINBOW_CTL2
	.byte $00	; $22 SPRSLOTID_RMRAINBOW_CTL3
	.byte $00	; $23 SPRSLOTID_RMRAINBOW_CTL4
	.byte $00	; $24 SPRSLOTID_SUBBOSS_KABATONCUE
	.byte $FF	; $25 SPRSLOTID_KABATONCUE_MISSILE
	.byte $00	; $26 SPRSLOTID_RINGMAN_UNK2
	.byte $FF	; $27 SPRSLOTID_WILY_ESCAPEPOD
	.byte $00	; $28 SPRSLOTID_BOMBABLE_WALL
	.byte $00	; $29 SPRSLOTID_MOTHRAYA_DIE
	.byte $00	; $2A SPRSLOTID_POWERGAIN_ORBS
	.byte $FF	; $2B SPRSLOTID_SUBBOSS_ESCAROO
	.byte $FF	; $2C SPRSLOTID_ESCAROO_BOMB
	.byte $00	; $2D SPRSLOTID_ESCAROO_DIE
	.byte $00	; $2E SPRSLOTID_EXPLODEYBIT
	.byte $00	; $2F SPRSLOTID_RED_UTRACK_PLAT
	.byte $FF	; $30 SPRSLOTID_SUBBOSS_WHOPPER
	.byte $00	; $31 SPRSLOTID_SUBBOSS_WHOPPER_RING
	.byte $FF	; $32 SPRSLOTID_SUBBOSS_WHOPPER_RIN2
	.byte $FF	; $33 SPRSLOTID_HAEHAEY
	.byte $FF	; $34 SPRSLOTID_HAEHAEY_SHOT
	.byte $FF	; $35 SPRSLOTID_RACKASER
	.byte $FF	; $36 SPRSLOTID_RACKASER_UMBRELLA
	.byte $FF	; $37 SPRSLOTID_DOMPAN
	.byte $00	; $38 SPRSLOTID_DOMPAN_FIREWORKS
	.byte $00	; $39 SPRSLOTID_CIRCLEBULLET
	.byte $00	; $3A SPRSLOTID_WHOPPER_DIE
	.byte $00	; $3B SPRSLOTID_CIRCULAREXPLOSION
	.byte $00	; $3C SPRSLOTID_CEXPLOSION
	.byte $FF	; $3D SPRSLOTID_MINOAN
	.byte $FF	; $3E SPRSLOTID_SUPERBALLMACHJR_L
	.byte $FF	; $3F SPRSLOTID_SUPERBALLMACHJR_B
	.byte $FF	; $40 SPRSLOTID_BOULDER_DISPENSER
	.byte $FF	; $41 SPRSLOTID_BOULDER_DEBRIS
	.byte $00	; $42 SPRSLOTID_EDDIE
	.byte $00	; $43 SPRSLOTID_EDDIE_IMMEDIATE
	.byte $00	; $44 SPRSLOTID_EDDIE_ITEM_EJECT
	.byte $FF	; $45 SPRSLOTID_CRPLATFORM_FALL
	.byte $FF	; $46 SPRSLOTID_JUMPBIG
	.byte $00	; $47
	.byte $FF	; $48 SPRSLOTID_SHIELDATTACKER
	.byte $FF	; $49 SPRSLOTID_COSSACK3BOSS1_DIE
	.byte $FF	; $4A SPRSLOTID_COSSACK3BOSS2_DIE
	.byte $00	; $4B SPRSLOTID_KABATONCUE_DIE
	.byte $00	; $4C SPRSLOTID_100WATTON_DIE
	.byte $00	; $4D SPRSLOTID_WILYCAPSULE_CHRG
	.byte $FF	; $4E SPRSLOTID_TOTEMPOLEN
	.byte $FF	; $4F SPRSLOTID_TOTEMPOLEN_SHOT
	.byte $FF	; $50 SPRSLOTID_METALL_1
	.byte $00	; $51 SPRSLOTID_METALL_BULLET
	.byte $FF	; $52 SPRSLOTID_SUBBOSS_MOBY
	.byte $FF	; $53 SPRSLOTID_MOBY_MISSILE
	.byte $FF	; $54 SPRSLOTID_MOBY_BIGSPIKE
	.byte $00	; $55
	.byte $FF	; $56 SPRSLOTID_METALL_2
	.byte $00	; $57
	.byte $00	; $58
	.byte $00	; $59
	.byte $00	; $5A
	.byte $00	; $5B SPRSLOTID_SWITCH
	.byte $FF	; $5C SPRSLOTID_METALL_3
	.byte $FF	; $5D SPRSLOTID_SINKINGPLATFORM
	.byte $00	; $5E SPRSLOTID_DUSTMAN_CRUSHERACT
	.byte $FF	; $5F SPRSLOTID_M422A
	.byte $00	; $60 SPRSLOTID_CINESTUFF
	.byte $FF	; $61 SPRSLOTID_PUYOYON
	.byte $FF	; $62 SPRSLOTID_SKELETONJOE
	.byte $FF	; $63 SPRSLOTID_SKELETONJOE_BONE
	.byte $FF	; $64 SPRSLOTID_RINGRING
	.byte $FF	; $65 SPRSLOTID_METALL_4
	.byte $00	; $66 SPRSLOTID_METALL_4_BUBBLE
	.byte $00	; $67 SPRSLOTID_WILY1_UNK1
	.byte $FF	; $68 SPRSLOTID_UNK68
	.byte $FF	; $69 SPRSLOTID_SKULLMET_R
	.byte $FF	; $6A SPRSLOTID_SKULLMET_BULLET
	.byte $00	; $6B SPRSLOTID_DIVEMAN_BIDIW1
	.byte $00	; $6C SPRSLOTID_DIVEMAN_BIDIW2
	.byte $FF	; $6D SPRSLOTID_HELIPON
	.byte $FF	; $6E SPRSLOTID_HELIPON_BULLET
	.byte $00	; $6F SPRSLOTID_WATERSPLASH
	.byte $FF	; $70 SPRSLOTID_GYOTOT
	.byte $00	; $71 SPRSLOTID_BOSSSKULL
	.byte $00	; $72 SPRSLOTID_SKULLMAN_BULLET
	.byte $00	; $73 SPRSLOTID_DUSTMAN_4PLAT
	.byte $00	; $74 SPRSLOTID_DUSTMAN_PLATSEG
	.byte $00	; $75 SPRSLOTID_BOSSRING
	.byte $00	; $76 SPRSLOTID_RINGMAN_RING
	.byte $00	; $77 SPRSLOTID_BOSSDEATH
	.byte $FF	; $78 SPRSLOTID_BIREE1
	.byte $00	; $79 SPRSLOTID_BOSSDUST
	.byte $00	; $7A SPRSLOTID_DUSTMAN_DUSTCRUSHER
	.byte $00	; $7B SPRSLOTID_DUSTMAN_DUSTDEBRIS
	.byte $00	; $7C SPRSLOTID_BOSSDIVE
	.byte $00	; $7D SPRSLOTID_BOSSDIVE_MISSILE
	.byte $00	; $7E SPRSLOTID_BOSSDRILL
	.byte $00	; $7F SPRSLOTID_DRILLMAN_DRILL
	.byte $00	; $80 SPRSLOTID_MISCSTUFF
	.byte $00	; $81 SPRSLOTID_BOSSINTRO
	.byte $00	; $82 SPRSLOTID_DRILLMAN_POOF
	.byte $00	; $83 SPRSLOTID_SPIRALEXPLOSION
	.byte $FF	; $84 SPRSLOTID_BOSSPHARAOH
	.byte $FF	; $85 SPRSLOTID_PHARAOHMAN_ATTACK
	.byte $FF	; $86 SPRSLOTID_PHARAOHMAN_SATTACK
	.byte $00	; $87 SPRSLOTID_BOSS_MOTHRAYA
	.byte $00	; $88 SPRSLOTID_COSSACK1_UNK1
	.byte $00	; $89 SPRSLOTID_COSSACK1_UNK2
	.byte $00	; $8A SPRSLOTID_MOTHRAYA_SHOT
	.byte $00	; $8B SPRSLOTID_BOSSBRIGHT
	.byte $00	; $8C SPRSLOTID_BOSSBRIGHT_BULLET
	.byte $00	; $8D SPRSLOTID_BOSSTOAD
	.byte $FF	; $8E SPRSLOTID_BATTONTON
	.byte $00	; $8F SPRSLOTID_MOTHRAYA_DEBRIS
	.byte $00	; $90 SPRSLOTID_EXPLODEY_DEATH
	.byte $FF	; $91 SPRSLOTID_MANTAN
	.byte $00	; $92 SPRSLOTID_BOSS_COSSACKCATCH
	.byte $00	; $93 SPRSLOTID_COSSACK4_UNK1
	.byte $00	; $94 SPRSLOTID_COSSACK4_BULLET
	.byte $00	; $95 SPRSLOTID_BOSS_SQUAREMACHINE
	.byte $00	; $96 SPRSLOTID_SQUAREMACH_PLATFORM
	.byte $00	; $97 SPRSLOTID_SQUAREMACHINE_SHOT
	.byte $FF	; $98 SPRSLOTID_BOULDER
	.byte $00	; $99 SPRSLOTID_COSSACK2_UNK2
	.byte $FF	; $9A SPRSLOTID_MUMMIRA
	.byte $00	; $9B SPRSLOTID_MUMMIRAHEAD
	.byte $FF	; $9C SPRSLOTID_IMORM
	.byte $00	; $9D SPRSLOTID_ENEMYEXPLODE
	.byte $00	; $9E SPRSLOTID_COSSACK3BOSS1
	.byte $00	; $9F SPRSLOTID_COSSACK3BOSS2_SHOT
	.byte $00	; $A0 SPRSLOTID_COSSACK3BOSS1_SHOT
	.byte $FF	; $A1 SPRSLOTID_MONOROADER
	.byte $00	; $A2 SPRSLOTID_COSSACK3BOSS2
	.byte $00	; $A3 SPRSLOTID_KALINKA
	.byte $00	; $A4 SPRSLOTID_PROTOMAN
	.byte $00	; $A5 SPRSLOTID_WILY
	.byte $00	; $A6 SPRSLOTID_BOSS_METALLDADDY
	.byte $FF	; $A7 SPRSLOTID_GACHAPPON
	.byte $00	; $A8 SPRSLOTID_GACHAPPON_BULLET
	.byte $00	; $A9 SPRSLOTID_GACHAPPON_GASHAPON
	.byte $FF	; $AA SPRSLOTID_METALLDADDY_METALL
	.byte $00	; $AB SPRSLOTID_BOSS_TAKOTRASH
	.byte $00	; $AC SPRSLOTID_WILY2_UNK1
	.byte $00	; $AD SPRSLOTID_TAKOTRASH_BALL
	.byte $00	; $AE SPRSLOTID_TAKOTRASH_FIREBALL
	.byte $00	; $AF SPRSLOTID_TAKOTRASH_PLATFORM
	.byte $FF	; $B0 SPRSLOTID_PAKATTO24
	.byte $FF	; $B1 SPRSLOTID_PAKATTO24_SHOT
	.byte $FF	; $B2 SPRSLOTID_UPNDOWN
	.byte $00	; $B3 SPRSLOTID_WILYTRANSPORTER
	.byte $00	; $B4 SPRSLOTID_UPNDOWN_SPAWNER
	.byte $00	; $B5 SPRSLOTID_SPIKEBLOCK_1
	.byte $FF	; $B6 SPRSLOTID_SEAMINE
	.byte $FF	; $B7 SPRSLOTID_GARYOBY
	.byte $00	; $B8 SPRSLOTID_BOSS_ROBOTMASTER
	.byte $FF	; $B9 SPRSLOTID_DOCRON
	.byte $FF	; $BA SPRSLOTID_DOCRON_SKULL
	.byte $00	; $BB SPRSLOTID_WILY3_UNK1
	.byte $00	; $BC SPRSLOTID_BOSS_WILYMACHINE4
	.byte $00	; $BD SPRSLOTID_TOGEHERO_SPAWNER_R
	.byte $FF	; $BE SPRSLOTID_TOGEHERO
	.byte $00	; $BF SPRSLOTID_WILYMACHINE4_SHOTCH
	.byte $00	; $C0 SPRSLOTID_WILYMACHINE4_PHASE2
	.byte $00	; $C1 SPRSLOTID_ITEM_PICKUP
	.byte $00	; $C2 SPRSLOTID_SPECWPN_PICKUP
	.byte $00	; $C3 SPRSLOTID_WILY1_DISPBLOCKS
	.byte $00	; $C4 SPRSLOTID_BOSS_WILYCAPSULE
	.byte $00	; $C5 SPRSLOTID_WILYCAPSULE_SHOT
	.byte $00	; $C6 SPRSLOTID_ITEM_PICKUP_GRAVITY
	.byte $00	; $C7 SPRSLOTID_LADDERPRESS_R
	.byte $00	; $C8 SPRSLOTID_DOMPAN_INTERWORK
	.byte $00	; $C9 SPRSLOTID_GREEN_UTRACK_PLAT
	.byte $00	; $CA SPRSLOTID_LADDERPRESS_L
	.byte $00	; $CB SPRSLOTID_WILYCAPSULE_DIE
	.byte $00	; $CC SPRSLOTID_DRILLMAN_POOF_ALT
	.byte $00	; $CD SPRSLOTID_TOADMAN_UNK1
	.byte $00	; $CE SPRSLOTID_TOGEHERO_SPAWNER_L
	.byte $00	; $CF SPRSLOTID_DIVEMAN_UNK5

	
	.byte $00, $00, $00, $00, $00, $00, $00	; $B7C7 - $B7D6
	.byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00	; $B7D7 - $B7E6
	.byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00	; $B7E7 - $B7F6
	.byte $00, $00, $00, $00, $00, $00, $00, $00, $00	; $B7F7 - $B7FF


	; CHR data shoved in here!
PRG044_B800:	.incchr "CHR/44_B800.pcx"
